// FrontendDevelopment_HandsOn/handson_08_vue/src/components/Header.vue
<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '@/stores/enrollment'

const store = useEnrollmentStore()
</script>

<template>
  <header class="site-header">
    <div class="site-name">Student Portal</div>
    <nav>
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile</RouterLink>
    </nav>
    <div class="enrolled-badge">Enrolled: {{ store.enrolledCourses.length }}</div>
  </header>
</template>

// FrontendDevelopment_HandsOn/handson_05_06_10_react/src/components/Header.jsx
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';

function Header({ siteName }) {
  const enrolledCourses = useSelector((state) => state.enrollment.enrolledCourses);

  return (
    <header className="site-header">
      <div className="site-name">{siteName}</div>
      <nav>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/courses">Courses</Link></li>
          <li><Link to="/profile">Profile</Link></li>
        </ul>
      </nav>
      <div className="enrolled-badge">Enrolled: {enrolledCourses.length}</div>
    </header>
  );
}

export default Header;
